//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: activity.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftGRPC
import SwiftProtobuf

internal protocol Com_Infinite_Travllr_ActivityServicesaveCall: ClientCallUnary {}

fileprivate final class Com_Infinite_Travllr_ActivityServicesaveCallBase: ClientCallUnaryBase<Com_Infinite_Travllr_ActivityInformation, Com_Infinite_Travllr_SaveActivityResponse>, Com_Infinite_Travllr_ActivityServicesaveCall {
  override class var method: String { return "/com.infinite.travllr.ActivityService/save" }
}

internal protocol Com_Infinite_Travllr_ActivityServicelistCall: ClientCallUnary {}

fileprivate final class Com_Infinite_Travllr_ActivityServicelistCallBase: ClientCallUnaryBase<Com_Infinite_Travllr_ActivityListRequest, Com_Infinite_Travllr_ActivityListResponse>, Com_Infinite_Travllr_ActivityServicelistCall {
  override class var method: String { return "/com.infinite.travllr.ActivityService/list" }
}

internal protocol Com_Infinite_Travllr_ActivityServicedeleteCall: ClientCallUnary {}

fileprivate final class Com_Infinite_Travllr_ActivityServicedeleteCallBase: ClientCallUnaryBase<Com_Infinite_Travllr_DeleteActivityRequest, Com_Infinite_Travllr_DeleteActivityResponse>, Com_Infinite_Travllr_ActivityServicedeleteCall {
  override class var method: String { return "/com.infinite.travllr.ActivityService/delete" }
}

internal protocol Com_Infinite_Travllr_ActivityServiceupdateCall: ClientCallUnary {}

fileprivate final class Com_Infinite_Travllr_ActivityServiceupdateCallBase: ClientCallUnaryBase<Com_Infinite_Travllr_ActivityInformation, Com_Infinite_Travllr_UpdateActivityResponse>, Com_Infinite_Travllr_ActivityServiceupdateCall {
  override class var method: String { return "/com.infinite.travllr.ActivityService/update" }
}


/// Instantiate Com_Infinite_Travllr_ActivityServiceServiceClient, then call methods of this protocol to make API calls.
internal protocol Com_Infinite_Travllr_ActivityServiceService: ServiceClient {
  /// Synchronous. Unary.
  func save(_ request: Com_Infinite_Travllr_ActivityInformation) throws -> Com_Infinite_Travllr_SaveActivityResponse
  /// Asynchronous. Unary.
  func save(_ request: Com_Infinite_Travllr_ActivityInformation, completion: @escaping (Com_Infinite_Travllr_SaveActivityResponse?, CallResult) -> Void) throws -> Com_Infinite_Travllr_ActivityServicesaveCall

  /// Synchronous. Unary.
  func list(_ request: Com_Infinite_Travllr_ActivityListRequest) throws -> Com_Infinite_Travllr_ActivityListResponse
  /// Asynchronous. Unary.
  func list(_ request: Com_Infinite_Travllr_ActivityListRequest, completion: @escaping (Com_Infinite_Travllr_ActivityListResponse?, CallResult) -> Void) throws -> Com_Infinite_Travllr_ActivityServicelistCall

  /// Synchronous. Unary.
  func delete(_ request: Com_Infinite_Travllr_DeleteActivityRequest) throws -> Com_Infinite_Travllr_DeleteActivityResponse
  /// Asynchronous. Unary.
  func delete(_ request: Com_Infinite_Travllr_DeleteActivityRequest, completion: @escaping (Com_Infinite_Travllr_DeleteActivityResponse?, CallResult) -> Void) throws -> Com_Infinite_Travllr_ActivityServicedeleteCall

  /// Synchronous. Unary.
  func update(_ request: Com_Infinite_Travllr_ActivityInformation) throws -> Com_Infinite_Travllr_UpdateActivityResponse
  /// Asynchronous. Unary.
  func update(_ request: Com_Infinite_Travllr_ActivityInformation, completion: @escaping (Com_Infinite_Travllr_UpdateActivityResponse?, CallResult) -> Void) throws -> Com_Infinite_Travllr_ActivityServiceupdateCall

}

internal final class Com_Infinite_Travllr_ActivityServiceServiceClient: ServiceClientBase, Com_Infinite_Travllr_ActivityServiceService {
  /// Synchronous. Unary.
  internal func save(_ request: Com_Infinite_Travllr_ActivityInformation) throws -> Com_Infinite_Travllr_SaveActivityResponse {
    return try Com_Infinite_Travllr_ActivityServicesaveCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func save(_ request: Com_Infinite_Travllr_ActivityInformation, completion: @escaping (Com_Infinite_Travllr_SaveActivityResponse?, CallResult) -> Void) throws -> Com_Infinite_Travllr_ActivityServicesaveCall {
    return try Com_Infinite_Travllr_ActivityServicesaveCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func list(_ request: Com_Infinite_Travllr_ActivityListRequest) throws -> Com_Infinite_Travllr_ActivityListResponse {
    return try Com_Infinite_Travllr_ActivityServicelistCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func list(_ request: Com_Infinite_Travllr_ActivityListRequest, completion: @escaping (Com_Infinite_Travllr_ActivityListResponse?, CallResult) -> Void) throws -> Com_Infinite_Travllr_ActivityServicelistCall {
    return try Com_Infinite_Travllr_ActivityServicelistCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func delete(_ request: Com_Infinite_Travllr_DeleteActivityRequest) throws -> Com_Infinite_Travllr_DeleteActivityResponse {
    return try Com_Infinite_Travllr_ActivityServicedeleteCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func delete(_ request: Com_Infinite_Travllr_DeleteActivityRequest, completion: @escaping (Com_Infinite_Travllr_DeleteActivityResponse?, CallResult) -> Void) throws -> Com_Infinite_Travllr_ActivityServicedeleteCall {
    return try Com_Infinite_Travllr_ActivityServicedeleteCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func update(_ request: Com_Infinite_Travllr_ActivityInformation) throws -> Com_Infinite_Travllr_UpdateActivityResponse {
    return try Com_Infinite_Travllr_ActivityServiceupdateCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func update(_ request: Com_Infinite_Travllr_ActivityInformation, completion: @escaping (Com_Infinite_Travllr_UpdateActivityResponse?, CallResult) -> Void) throws -> Com_Infinite_Travllr_ActivityServiceupdateCall {
    return try Com_Infinite_Travllr_ActivityServiceupdateCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

}

