//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: admin.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftGRPC
import SwiftProtobuf

internal protocol Com_Infinite_Travllr_AdminServiceloginCall: ClientCallUnary {}

fileprivate final class Com_Infinite_Travllr_AdminServiceloginCallBase: ClientCallUnaryBase<Com_Infinite_Travllr_UserLogin, Com_Infinite_Travllr_UserLoginResponse>, Com_Infinite_Travllr_AdminServiceloginCall {
  override class var method: String { return "/com.infinite.travllr.AdminService/login" }
}

internal protocol Com_Infinite_Travllr_AdminServicecreateUserCall: ClientCallUnary {}

fileprivate final class Com_Infinite_Travllr_AdminServicecreateUserCallBase: ClientCallUnaryBase<Com_Infinite_Travllr_UserRequest, Com_Infinite_Travllr_CreateUserResponse>, Com_Infinite_Travllr_AdminServicecreateUserCall {
  override class var method: String { return "/com.infinite.travllr.AdminService/createUser" }
}

internal protocol Com_Infinite_Travllr_AdminServicelistCall: ClientCallUnary {}

fileprivate final class Com_Infinite_Travllr_AdminServicelistCallBase: ClientCallUnaryBase<Com_Infinite_Travllr_UserListRequest, Com_Infinite_Travllr_UserListResponse>, Com_Infinite_Travllr_AdminServicelistCall {
  override class var method: String { return "/com.infinite.travllr.AdminService/list" }
}

internal protocol Com_Infinite_Travllr_AdminServiceeditCall: ClientCallUnary {}

fileprivate final class Com_Infinite_Travllr_AdminServiceeditCallBase: ClientCallUnaryBase<Com_Infinite_Travllr_UserRequest, Com_Infinite_Travllr_EditUserInfoResponse>, Com_Infinite_Travllr_AdminServiceeditCall {
  override class var method: String { return "/com.infinite.travllr.AdminService/edit" }
}

internal protocol Com_Infinite_Travllr_AdminServiceaccessCall: ClientCallUnary {}

fileprivate final class Com_Infinite_Travllr_AdminServiceaccessCallBase: ClientCallUnaryBase<Com_Infinite_Travllr_EditUserAccessRequest, Com_Infinite_Travllr_EditUserAccessResponse>, Com_Infinite_Travllr_AdminServiceaccessCall {
  override class var method: String { return "/com.infinite.travllr.AdminService/access" }
}


/// Instantiate Com_Infinite_Travllr_AdminServiceServiceClient, then call methods of this protocol to make API calls.
internal protocol Com_Infinite_Travllr_AdminServiceService: ServiceClient {
  /// Synchronous. Unary.
  func login(_ request: Com_Infinite_Travllr_UserLogin) throws -> Com_Infinite_Travllr_UserLoginResponse
  /// Asynchronous. Unary.
  func login(_ request: Com_Infinite_Travllr_UserLogin, completion: @escaping (Com_Infinite_Travllr_UserLoginResponse?, CallResult) -> Void) throws -> Com_Infinite_Travllr_AdminServiceloginCall

  /// Synchronous. Unary.
  func createUser(_ request: Com_Infinite_Travllr_UserRequest) throws -> Com_Infinite_Travllr_CreateUserResponse
  /// Asynchronous. Unary.
  func createUser(_ request: Com_Infinite_Travllr_UserRequest, completion: @escaping (Com_Infinite_Travllr_CreateUserResponse?, CallResult) -> Void) throws -> Com_Infinite_Travllr_AdminServicecreateUserCall

  /// Synchronous. Unary.
  func list(_ request: Com_Infinite_Travllr_UserListRequest) throws -> Com_Infinite_Travllr_UserListResponse
  /// Asynchronous. Unary.
  func list(_ request: Com_Infinite_Travllr_UserListRequest, completion: @escaping (Com_Infinite_Travllr_UserListResponse?, CallResult) -> Void) throws -> Com_Infinite_Travllr_AdminServicelistCall

  /// Synchronous. Unary.
  func edit(_ request: Com_Infinite_Travllr_UserRequest) throws -> Com_Infinite_Travllr_EditUserInfoResponse
  /// Asynchronous. Unary.
  func edit(_ request: Com_Infinite_Travllr_UserRequest, completion: @escaping (Com_Infinite_Travllr_EditUserInfoResponse?, CallResult) -> Void) throws -> Com_Infinite_Travllr_AdminServiceeditCall

  /// Synchronous. Unary.
  func access(_ request: Com_Infinite_Travllr_EditUserAccessRequest) throws -> Com_Infinite_Travllr_EditUserAccessResponse
  /// Asynchronous. Unary.
  func access(_ request: Com_Infinite_Travllr_EditUserAccessRequest, completion: @escaping (Com_Infinite_Travllr_EditUserAccessResponse?, CallResult) -> Void) throws -> Com_Infinite_Travllr_AdminServiceaccessCall

}

internal final class Com_Infinite_Travllr_AdminServiceServiceClient: ServiceClientBase, Com_Infinite_Travllr_AdminServiceService {
  /// Synchronous. Unary.
  internal func login(_ request: Com_Infinite_Travllr_UserLogin) throws -> Com_Infinite_Travllr_UserLoginResponse {
    return try Com_Infinite_Travllr_AdminServiceloginCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func login(_ request: Com_Infinite_Travllr_UserLogin, completion: @escaping (Com_Infinite_Travllr_UserLoginResponse?, CallResult) -> Void) throws -> Com_Infinite_Travllr_AdminServiceloginCall {
    return try Com_Infinite_Travllr_AdminServiceloginCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func createUser(_ request: Com_Infinite_Travllr_UserRequest) throws -> Com_Infinite_Travllr_CreateUserResponse {
    return try Com_Infinite_Travllr_AdminServicecreateUserCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func createUser(_ request: Com_Infinite_Travllr_UserRequest, completion: @escaping (Com_Infinite_Travllr_CreateUserResponse?, CallResult) -> Void) throws -> Com_Infinite_Travllr_AdminServicecreateUserCall {
    return try Com_Infinite_Travllr_AdminServicecreateUserCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func list(_ request: Com_Infinite_Travllr_UserListRequest) throws -> Com_Infinite_Travllr_UserListResponse {
    return try Com_Infinite_Travllr_AdminServicelistCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func list(_ request: Com_Infinite_Travllr_UserListRequest, completion: @escaping (Com_Infinite_Travllr_UserListResponse?, CallResult) -> Void) throws -> Com_Infinite_Travllr_AdminServicelistCall {
    return try Com_Infinite_Travllr_AdminServicelistCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func edit(_ request: Com_Infinite_Travllr_UserRequest) throws -> Com_Infinite_Travllr_EditUserInfoResponse {
    return try Com_Infinite_Travllr_AdminServiceeditCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func edit(_ request: Com_Infinite_Travllr_UserRequest, completion: @escaping (Com_Infinite_Travllr_EditUserInfoResponse?, CallResult) -> Void) throws -> Com_Infinite_Travllr_AdminServiceeditCall {
    return try Com_Infinite_Travllr_AdminServiceeditCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func access(_ request: Com_Infinite_Travllr_EditUserAccessRequest) throws -> Com_Infinite_Travllr_EditUserAccessResponse {
    return try Com_Infinite_Travllr_AdminServiceaccessCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func access(_ request: Com_Infinite_Travllr_EditUserAccessRequest, completion: @escaping (Com_Infinite_Travllr_EditUserAccessResponse?, CallResult) -> Void) throws -> Com_Infinite_Travllr_AdminServiceaccessCall {
    return try Com_Infinite_Travllr_AdminServiceaccessCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

}

