//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: airline.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftGRPC
import SwiftProtobuf

internal protocol Com_Infinite_Travllr_Airline_AirlineServicegetFlightsCall: ClientCallUnary {}

fileprivate final class Com_Infinite_Travllr_Airline_AirlineServicegetFlightsCallBase: ClientCallUnaryBase<Com_Infinite_Travllr_Airline_AirlineRequest, Com_Infinite_Travllr_Airline_AirlineResponse>, Com_Infinite_Travllr_Airline_AirlineServicegetFlightsCall {
  override class var method: String { return "/com.infinite.travllr.airline.AirlineService/getFlights" }
}


/// Instantiate Com_Infinite_Travllr_Airline_AirlineServiceServiceClient, then call methods of this protocol to make API calls.
internal protocol Com_Infinite_Travllr_Airline_AirlineServiceService: ServiceClient {
  /// Synchronous. Unary.
  func getFlights(_ request: Com_Infinite_Travllr_Airline_AirlineRequest) throws -> Com_Infinite_Travllr_Airline_AirlineResponse
  /// Asynchronous. Unary.
  func getFlights(_ request: Com_Infinite_Travllr_Airline_AirlineRequest, completion: @escaping (Com_Infinite_Travllr_Airline_AirlineResponse?, CallResult) -> Void) throws -> Com_Infinite_Travllr_Airline_AirlineServicegetFlightsCall

}

internal final class Com_Infinite_Travllr_Airline_AirlineServiceServiceClient: ServiceClientBase, Com_Infinite_Travllr_Airline_AirlineServiceService {
  /// Synchronous. Unary.
  internal func getFlights(_ request: Com_Infinite_Travllr_Airline_AirlineRequest) throws -> Com_Infinite_Travllr_Airline_AirlineResponse {
    return try Com_Infinite_Travllr_Airline_AirlineServicegetFlightsCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func getFlights(_ request: Com_Infinite_Travllr_Airline_AirlineRequest, completion: @escaping (Com_Infinite_Travllr_Airline_AirlineResponse?, CallResult) -> Void) throws -> Com_Infinite_Travllr_Airline_AirlineServicegetFlightsCall {
    return try Com_Infinite_Travllr_Airline_AirlineServicegetFlightsCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

}

