//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: user.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftGRPC
import SwiftProtobuf

internal protocol Com_Infinite_Travllr_UserServiceuserListCall: ClientCallUnary {}

fileprivate final class Com_Infinite_Travllr_UserServiceuserListCallBase: ClientCallUnaryBase<Com_Infinite_Travllr_Empty, Com_Infinite_Travllr_UserList>, Com_Infinite_Travllr_UserServiceuserListCall {
  override class var method: String { return "/com.infinite.travllr.UserService/userList" }
}

internal protocol Com_Infinite_Travllr_UserServiceuserDetailCall: ClientCallUnary {}

fileprivate final class Com_Infinite_Travllr_UserServiceuserDetailCallBase: ClientCallUnaryBase<Com_Infinite_Travllr_UserDetailRequest, Com_Infinite_Travllr_UserDetailResponse>, Com_Infinite_Travllr_UserServiceuserDetailCall {
  override class var method: String { return "/com.infinite.travllr.UserService/userDetail" }
}


/// Instantiate Com_Infinite_Travllr_UserServiceServiceClient, then call methods of this protocol to make API calls.
internal protocol Com_Infinite_Travllr_UserServiceService: ServiceClient {
  /// Synchronous. Unary.
  func userList(_ request: Com_Infinite_Travllr_Empty) throws -> Com_Infinite_Travllr_UserList
  /// Asynchronous. Unary.
  func userList(_ request: Com_Infinite_Travllr_Empty, completion: @escaping (Com_Infinite_Travllr_UserList?, CallResult) -> Void) throws -> Com_Infinite_Travllr_UserServiceuserListCall

  /// Synchronous. Unary.
  func userDetail(_ request: Com_Infinite_Travllr_UserDetailRequest) throws -> Com_Infinite_Travllr_UserDetailResponse
  /// Asynchronous. Unary.
  func userDetail(_ request: Com_Infinite_Travllr_UserDetailRequest, completion: @escaping (Com_Infinite_Travllr_UserDetailResponse?, CallResult) -> Void) throws -> Com_Infinite_Travllr_UserServiceuserDetailCall

}

internal final class Com_Infinite_Travllr_UserServiceServiceClient: ServiceClientBase, Com_Infinite_Travllr_UserServiceService {
  /// Synchronous. Unary.
  internal func userList(_ request: Com_Infinite_Travllr_Empty) throws -> Com_Infinite_Travllr_UserList {
    return try Com_Infinite_Travllr_UserServiceuserListCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func userList(_ request: Com_Infinite_Travllr_Empty, completion: @escaping (Com_Infinite_Travllr_UserList?, CallResult) -> Void) throws -> Com_Infinite_Travllr_UserServiceuserListCall {
    return try Com_Infinite_Travllr_UserServiceuserListCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func userDetail(_ request: Com_Infinite_Travllr_UserDetailRequest) throws -> Com_Infinite_Travllr_UserDetailResponse {
    return try Com_Infinite_Travllr_UserServiceuserDetailCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func userDetail(_ request: Com_Infinite_Travllr_UserDetailRequest, completion: @escaping (Com_Infinite_Travllr_UserDetailResponse?, CallResult) -> Void) throws -> Com_Infinite_Travllr_UserServiceuserDetailCall {
    return try Com_Infinite_Travllr_UserServiceuserDetailCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

}

